export { getPool, closePool } from './client.js';
export {
  getActiveUsers,
  getUserById,
  getUserByTelegramChatId,
  getUserByTecUsername,
  createUser,
  updateUser,
  updateUserCredentials,
  updateUserDriveFolder,
  updateUserOneDriveFolder,
  updateUserStorageProvider,
  notificationExists,
  getNotificationState,
  insertNotification,
  updateNotificationDocumentStatus,
  listUserNotificationCourses,
  uploadedFileExists,
  insertUploadedFile,
  listUserCourseFilters,
  muteUserCourse,
  unmuteUserCourse,
  unmuteUserCourses,
  isCourseMuted,
  isAnyCourseMuted,
  resolveCourseEntry,
  getCourseCodeByName,
  getOneDriveOAuthToken,
  saveOneDriveOAuthToken,
  getDriveOAuthToken,
  saveDriveOAuthToken,
  createOAuthState,
  consumeOAuthState,
  purgeExpiredOAuthStates,
  upsertCourseMapping,
  getCourseMapping,
  getPendingRegistration,
  upsertPendingRegistration,
  upsertPendingRegistrationWithStep,
  advancePendingRegistration,
  deletePendingRegistration,
  type PendingRegistration,
  type RegistrationStep,
  getAdminStats,
  type AdminStats,
} from './queries.js';
export { runMigrations } from './migrate.js';
export { encrypt, decrypt, reEncryptLegacyCbcRows } from './crypto.js';
export { normalizeCourseKey, normalizeCourseLabel } from './queries.js';
